"""The movies: slice each `__STR/*.IKI` off the import, decode it, and keep the list.

    ./make.sh movies            every movie into work/movies/<name>.avi, narration muxed in
    ./make.sh movies --tsv      just regenerate research/data/movies.tsv

An `.IKI` is real-time interleaved -- Form 1 video sectors and Form 2 XA audio sectors
alternate inside one extent by subheader channel -- so `boku import` does not extract it
(`boku.importer._is_cooked_file`) and 2048 bytes a sector is not its byte stream. What a
decoder needs is the extent's **raw** 2352-byte sectors, which is all `slice_movie` does.

Decoding is jPSXdec's job: ffmpeg demuxes an `.IKI` but its MDEC decoder rejects every IKI
frame, and it has no STR encoder either (`research/movies.md` § 4, which is the one home
for the install path and the flags). We ask for `-vf avi:mjpg -q psx -psxav` -- the same
decode `research/movies.md` § 4 names as the reference for timing -- and leave the XA
audio muxed in, because the narration is the point of watching these at all. AVI and not
mp4: this is jPSXdec's own one-step output, so the picture is compressed once rather than
twice, and VLC plays it as-is.

`research/data/movies.tsv` is the list, and it is generated rather than typed. The file's
own header says which column comes from where; `build_tsv` is where that is done.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
from collections import Counter
from collections.abc import Iterable, Iterator
from dataclasses import dataclass
from pathlib import Path

from boku import REPO_ROOT
from boku.disc import DiscError, DiscImage

DEFAULT_IMAGE = REPO_ROOT / "disc" / "image.img"
DEFAULT_OUT_DIR = REPO_ROOT / "work" / "movies"
MOVIES_MD = REPO_ROOT / "research" / "movies.md"
SCENE_EDGES_TSV = REPO_ROOT / "research" / "data" / "scene-edges.tsv"
MOVIES_TSV = REPO_ROOT / "research" / "data" / "movies.tsv"

STR_DIR = "/__STR"
IKI_SUFFIX = ".IKI"

SECTORS_PER_FRAME = 10
"""Measured on this disc: every `.IKI` extent is a whole number of 10-sector frame slots
(`research/movies.md` § 4, which is that fact's home; jPSXdec's index says
`Sectors/Frame:10/1`). `decode_one` refuses a movie whose index disagrees, so the
arithmetic below is never taken on trust."""

FPS = 15
"""2x disc speed, 10 sectors a frame (`research/movies.md` § 4)."""

_SLICE_CHUNK_SECTORS = 4096
"""9.6 MB a read. Measured 2026-09-22: the 99.8 MB `M27` extent slices in 0.05 s, about
2 GB/s, so the loop is already at device speed and a larger buffer buys nothing."""

JAVA_CANDIDATES = ("/opt/homebrew/opt/openjdk@21/bin/java", "java")
"""macOS's `/usr/bin/java` is a stub that refuses; the Homebrew JDK the jPSXdec notes name
is tried first. `$BOKU_JAVA` overrides both."""

JAVA_ENV = "BOKU_JAVA"
JPSXDEC_ENV = "BOKU_JPSXDEC_JAR"
DEFAULT_JPSXDEC_JAR = Path.home() / "Dev/dist/jpsxdec/jpsxdec_v2.1-beta/jpsxdec.jar"

TSV_HEADER_COMMENT = """\
# The movies, one row per `MOVIE` id. Generated by `./make.sh movies`; research/movies.md
# section 1 is where the columns come from and what they mean.
#
# what_it_shows is BLANK ON PURPOSE: Jay fills it in from watching work/movies/<file>.avi,
# which `./make.sh movies` writes. It and notes are the only hand-written columns, and a
# regeneration carries them across unchanged; every other column is overwritten.
"""

COLUMNS = (
    "id",
    "file",
    "frames",
    "seconds",
    "stop_frame",
    "skippable",
    "shares_file_with",
    "issued_by",
    "what_it_shows",
    "notes",
)
HAND_COLUMNS = ("what_it_shows", "notes")

NO_ISSUER = "none found"


class MovieError(Exception):
    """Something the movies step cannot do, for a reason the message states in full."""


# --- the disc: one raw slice per .IKI ------------------------------------------------------------


@dataclass(frozen=True)
class MovieFile:
    """One `.IKI` extent: where it starts, how long it is, and what it is called.

    `sectors` is the extent's whole length, video and interleaved audio together -- not a
    Form 1 byte count, which an interleaved extent does not have.
    """

    name: str
    path: str
    lba: int
    sectors: int

    @property
    def frames(self) -> int:
        """Frame slots in the extent. See `SECTORS_PER_FRAME` for why this is division."""
        if self.sectors % SECTORS_PER_FRAME:
            raise MovieError(
                f"{self.path} spans {self.sectors} sectors, which is not a whole number of "
                f"{SECTORS_PER_FRAME}-sector frame slots -- research/movies.md section 4"
            )
        return self.sectors // SECTORS_PER_FRAME


def iki_entries(image: DiscImage) -> list[MovieFile]:
    """Every `__STR/*.IKI` on the image, in name order."""
    found = [
        MovieFile(
            name=entry.name[: -len(IKI_SUFFIX)],
            path=entry.path,
            lba=entry.lba,
            sectors=entry.sector_count,
        )
        for entry in image.walk()
        if not entry.is_dir
        and entry.path.startswith(f"{STR_DIR}/")
        and entry.name.upper().endswith(IKI_SUFFIX)
    ]
    if not found:
        raise MovieError(f"no {STR_DIR}/*{IKI_SUFFIX} on {image.path}: is this the right image?")
    return sorted(found, key=lambda movie: movie.name)


def slice_movie(image: DiscImage, movie: MovieFile, out_path: Path) -> int:
    """Write the movie's extent as raw 2352-byte sectors, and return how many.

    Raw and not cooked: the audio lives in the Form 2 sectors between the video ones, and
    a decoder reads the subheaders to tell them apart.
    """
    written = 0
    with out_path.open("wb") as handle:
        while written < movie.sectors:
            batch = min(_SLICE_CHUNK_SECTORS, movie.sectors - written)
            handle.write(image.read_raw(movie.lba + written, batch))
            written += batch
    return written


# --- research/movies.md: the executable's own table -----------------------------------------------


@dataclass(frozen=True)
class MovieId:
    """One row of `g_movie_table`: which file this id plays and where it stops."""

    id: int
    file: str
    stop_frame: int


def _section(note: str, heading_prefix: str) -> str:
    """The text of the `##` section whose heading starts with `heading_prefix`."""
    lines = note.splitlines()
    for start, line in enumerate(lines):
        if line.startswith("## ") and line[3:].startswith(heading_prefix):
            end = next(
                (i for i in range(start + 1, len(lines)) if lines[i].startswith("## ")),
                len(lines),
            )
            return "\n".join(lines[start:end])
    raise MovieError(f"{MOVIES_MD.name} has no section starting '## {heading_prefix}'")


def _plain(cell: str) -> str:
    """A markdown table cell as its value: no emphasis, no code ticks, no padding."""
    return cell.replace("**", "").replace("`", "").strip()


def _table_rows(section: str) -> Iterator[list[str]]:
    """The data rows of the FIRST markdown table in `section`, as plain cells.

    It stops at the line that ends that table, because `research/movies.md` has several
    tables per section (§ 2.2's frame loop, § 4's quality figures) and rows of a second
    one reaching `parse_movie_ids` would be read as `g_movie_table` entries.
    """
    started = False
    for line in section.splitlines():
        if not line.startswith("|"):
            if started:
                return
            continue
        started = True
        cells = [_plain(cell) for cell in line.strip().strip("|").split("|")]
        if not cells or set("".join(cells)) <= set("-: "):
            continue  # the separator row
        if cells[0] == "id":
            continue  # the header row
        yield cells


def parse_movie_ids(note: str) -> list[MovieId]:
    """`research/movies.md` § 1's table, one entry per `MOVIE` id.

    A row may carry several ids -- `| 2, 3 | M031, M032 | 47 |` -- in which case each
    further column is either one value shared by all of them or one value each. Anything
    else is refused rather than silently paired off, because a mis-pairing here points a
    whole row of the list at the wrong file.
    """
    entries: list[MovieId] = []
    for cells in _table_rows(_section(note, "1.")):
        if len(cells) < 3:
            raise MovieError(f"movies.md section 1: row {cells!r} has fewer than 3 columns")
        try:
            ids = [int(part) for part in cells[0].split(",")]
        except ValueError:
            raise MovieError(f"movies.md section 1: {cells[0]!r} is not a list of ids") from None
        files = _spread(cells[1].split(","), ids, "file", cells)
        try:
            stops = [int(stop) for stop in _spread(cells[2].split(","), ids, "stop frame", cells)]
        except ValueError:
            raise MovieError(
                f"movies.md section 1: {cells[2]!r} is not a list of stop frames"
            ) from None
        entries += [
            MovieId(id=i, file=f.strip(), stop_frame=s)
            for i, f, s in zip(ids, files, stops, strict=True)
        ]
    _refuse_bad_id_set([entry.id for entry in entries])
    return sorted(entries, key=lambda entry: entry.id)


def _spread(values: list[str], ids: list[int], what: str, row: list[str]) -> list[str]:
    values = [value.strip() for value in values]
    if len(values) == 1:
        return values * len(ids)
    if len(values) != len(ids):
        raise MovieError(
            f"movies.md section 1: row {row!r} names {len(ids)} ids and {len(values)} "
            f"{what} values, so which {what} belongs to which id is not stated"
        )
    return values


def _refuse_bad_id_set(ids: list[int]) -> None:
    duplicates = sorted(i for i, seen in Counter(ids).items() if seen > 1)
    if duplicates:
        raise MovieError(f"movies.md section 1: ids {duplicates} appear in more than one row")
    if sorted(ids) != list(range(len(ids))):
        raise MovieError(
            f"movies.md section 1: the ids are not 0..{len(ids) - 1} with no gaps; "
            f"got {sorted(ids)}"
        )


_ARROW = "\u2192"
_SKIP_SENTENCE = re.compile(
    # The whole sentence, to its full stop or its parenthesis -- not just as far as the
    # default clause. Stopping there would drop anything stated after it, and appending is
    # where an English sentence naturally grows.
    rf"ids [^:.]*?{_ARROW}[^:.]*?(?=\s*[.(])",
    re.IGNORECASE,
)
_MASK = re.compile(r"`?(0x[0-9a-f]+|0)`?\s*$", re.IGNORECASE)


def parse_skip_masks(note: str, ids: Iterable[int]) -> dict[int, int]:
    """The per-id pad mask `movie_set_skip_mask` installs, from § 2.1's own sentence.

    Mask 0 is the one that matters to a viewer: that movie cannot be skipped. Every clause
    of the sentence has to be consumed, and the default one is not allowed to be the last
    word on the subject -- see `_SKIP_SENTENCE`.
    """
    section = _section(note, "2.")
    sentence = _SKIP_SENTENCE.search(" ".join(section.split()).replace("->", _ARROW))
    if sentence is None or "every other id" not in sentence.group(0):
        raise MovieError(
            "movies.md section 2.1 no longer states the skip masks in the form "
            "'ids <list> -> <mask>; ...; every other id -> <mask>'"
        )
    masks: dict[int, int] = {}
    default: int | None = None
    for clause in sentence.group(0).split(";"):
        clause = clause.strip()
        head, _, tail = clause.partition(_ARROW)
        mask_text = _MASK.search(tail.strip())
        if mask_text is None:
            raise MovieError(f"movies.md section 2.1: {clause!r} does not end in a mask")
        mask = int(mask_text.group(1), 0)
        head = head.strip().removeprefix("ids").strip()
        if head.startswith("every other id"):
            default = mask
            continue
        for member in _expand_id_list(head, clause):
            masks[member] = mask
    if default is None:
        raise MovieError("movies.md section 2.1: the skip-mask sentence states no default")
    return {i: masks.get(i, default) for i in ids}


def _expand_id_list(text: str, clause: str) -> list[int]:
    """`1-5, 16, 17, 20` -> the ids it names.

    A hyphen, an en dash or an em dash is a range: `boku.packets._expand_bases` measured
    that the notes in this repo are written with all three.
    """
    out: list[int] = []
    for token in text.split(","):
        token = token.strip().replace("\u2013", "-").replace("\u2014", "-")
        try:
            if "-" in token:
                low, high = (int(part) for part in token.split("-", 1))
                out += list(range(low, high + 1))
            else:
                out.append(int(token))
        except ValueError:
            raise MovieError(
                f"movies.md section 2.1: {token!r} in {clause!r} is not an id"
            ) from None
    return out


# --- research/data/scene-edges.tsv: who issues which movie ----------------------------------------

_MOVIE_NODE = re.compile(r"MOVIE(\d+):")


def parse_issuers(edges_tsv: str) -> dict[int, list[str]]:
    """Movie id -> the events whose `MOVIE` opcode issues it, from the scene graph.

    The edge walker writes a `MOVIE<id>:<return map>` node for every `MOVIE` opcode
    (`boku.research.scene_row`), so the graph is the one home for this and § 1's "issued
    by" column is the same derivation written out.
    """
    issuers: dict[int, set[str]] = {}
    for line in edges_tsv.splitlines()[1:]:
        fields = line.split("\t")
        if len(fields) < 3:
            continue
        for node in fields[1:3]:
            for match in _MOVIE_NODE.finditer(node):
                issuers.setdefault(int(match.group(1)), set()).add(fields[0])
    return {movie: sorted(events) for movie, events in issuers.items()}


# --- research/data/movies.tsv ---------------------------------------------------------------------


def read_hand_columns(tsv: str) -> dict[int, dict[str, str]]:
    """The hand-written columns of an existing table, by id -- what a regeneration keeps."""
    rows = [line for line in tsv.splitlines() if line and not line.startswith("#")]
    if not rows:
        return {}
    header = rows[0].split("\t")
    kept: dict[int, dict[str, str]] = {}
    for row in rows[1:]:
        fields = row.split("\t")
        if len(fields) != len(header):
            # A tab typed into what_it_shows shifts every column after it. Tolerating that
            # loses `notes` on the next regeneration, silently, which is the one thing this
            # file exists to hold on to.
            raise MovieError(
                f"{MOVIES_TSV.name}: a row has {len(fields)} columns and the header has "
                f"{len(header)} -- a tab in a hand-written column, most likely. The row "
                f"starts {row[:60]!r}"
            )
        by_name = dict(zip(header, fields, strict=True))
        try:
            movie = int(by_name["id"])
        except (KeyError, ValueError):
            raise MovieError(f"{MOVIES_TSV.name}: row {row!r} has no id") from None
        kept[movie] = {
            column: by_name.get(column, "") for column in HAND_COLUMNS if column in header
        }
    return kept


def build_tsv(
    note: str,
    edges_tsv: str,
    frames_by_file: dict[str, int],
    previous: str = "",
    entries: list[MovieId] | None = None,
) -> str:
    """The whole table: derived columns regenerated, hand-written columns carried across."""
    if entries is None:
        entries = parse_movie_ids(note)
    masks = parse_skip_masks(note, [entry.id for entry in entries])
    issuers = parse_issuers(edges_tsv)
    kept = read_hand_columns(previous)
    shared: dict[str, list[int]] = {}
    for entry in entries:
        shared.setdefault(entry.file, []).append(entry.id)

    lines = [TSV_HEADER_COMMENT.rstrip("\n"), "\t".join(COLUMNS)]
    for entry in entries:
        if entry.file not in frames_by_file:
            raise MovieError(
                f"movies.md section 1 names {entry.file} for id {entry.id}, but there is no "
                f"{STR_DIR}/{entry.file}{IKI_SUFFIX} on the image"
            )
        hand = kept.get(entry.id, {})
        lines.append(
            "\t".join(
                [
                    str(entry.id),
                    entry.file,
                    str(frames_by_file[entry.file]),
                    f"{entry.stop_frame / FPS:.1f}",
                    str(entry.stop_frame),
                    "yes" if masks[entry.id] else "no",
                    ",".join(str(i) for i in shared[entry.file] if i != entry.id) or "-",
                    ",".join(issuers.get(entry.id, [])) or NO_ISSUER,
                    hand.get("what_it_shows", ""),
                    hand.get("notes", ""),
                ]
            )
        )
    return "\n".join(lines) + "\n"


def write_tsv(
    frames_by_file: dict[str, int],
    path: Path = MOVIES_TSV,
    *,
    entries: list[MovieId] | None = None,
) -> Path:
    """Regenerate `path` in place, keeping whatever hand-written columns it already holds."""
    previous = path.read_text(encoding="utf-8") if path.is_file() else ""
    path.write_text(
        build_tsv(
            MOVIES_MD.read_text(encoding="utf-8"),
            SCENE_EDGES_TSV.read_text(encoding="utf-8"),
            frames_by_file,
            previous,
            entries=entries,
        ),
        encoding="utf-8",
    )
    return path


def ids_by_file(entries: list[MovieId]) -> dict[str, list[int]]:
    """File name -> the `MOVIE` ids that play it: three ids share `M27`."""
    out: dict[str, list[int]] = {}
    for entry in entries:
        out.setdefault(entry.file, []).append(entry.id)
    return out


# --- jPSXdec ------------------------------------------------------------------------------------


def java_binary(override: str | None = None) -> str:
    """The JDK to run jPSXdec under. An explicit choice is obeyed or refused, never fallen
    back from: quietly running a *different* Java than the one that was named is how a
    machine-specific failure gets diagnosed against the wrong runtime."""
    chosen = override or os.environ.get(JAVA_ENV)
    if chosen:
        found = shutil.which(chosen)
        if found:
            return found
        raise MovieError(f"${JAVA_ENV} is {chosen!r}, which is not a runnable Java")
    for candidate in JAVA_CANDIDATES:
        found = shutil.which(candidate)
        if found:
            return found
    raise MovieError(
        f"no Java runtime: tried {', '.join(JAVA_CANDIDATES)}. macOS ships a stub at "
        f"/usr/bin/java that refuses to run; install the Homebrew OpenJDK 21 that "
        f"research/movies.md section 4 names, or set ${JAVA_ENV}"
    )


def jpsxdec_jar(override: Path | None = None) -> Path:
    """The jar to decode with. Like `java_binary`, an explicit choice is obeyed or refused."""
    from_env = os.environ.get(JPSXDEC_ENV)
    chosen = override or (Path(from_env) if from_env else None)
    jar = chosen or DEFAULT_JPSXDEC_JAR
    if jar.is_file():
        return jar
    if chosen is not None:
        raise MovieError(f"${JPSXDEC_ENV} is {str(jar)!r}, and there is no jar there")
    raise MovieError(
        f"no jPSXdec jar at {jar}: install it where research/movies.md section 4 says, "
        f"or set ${JPSXDEC_ENV}. ffmpeg cannot decode IKI video, so there is no fallback"
    )


@dataclass(frozen=True)
class IndexItem:
    """One line of a jPSXdec index file, as its `Key:value|Key:value` fields."""

    fields: dict[str, str]

    @property
    def number(self) -> int:
        return int(self.fields["#"])

    @property
    def type(self) -> str:
        return self.fields.get("Type", "")


def parse_index(index_text: str) -> list[IndexItem]:
    items = []
    for line in index_text.splitlines():
        if not line.startswith("#:"):
            continue
        fields: dict[str, str] = {}
        for part in line.split("|"):
            key, _, value = part.partition(":")
            fields[key.strip()] = value.strip()
        items.append(IndexItem(fields=fields))
    return items


def _run(command: list[str], cwd: Path, what: str) -> str:
    try:
        result = subprocess.run(command, cwd=cwd, capture_output=True, text=True, check=False)
    except OSError as missing:
        # Without this the tool dies with a traceback past `main_movies`'s except clause.
        raise MovieError(f"{what}: could not run {command[0]} -- {missing}") from None
    if result.returncode != 0:
        raise MovieError(
            f"{what} failed (exit {result.returncode}):\n"
            f"  {' '.join(command)}\n{result.stdout}\n{result.stderr}"
        )
    return result.stdout


def ffprobe_streams(path: Path) -> list[dict[str, str]]:
    """Every stream of `path` -- the check that the file really opens.

    JSON rather than ffprobe's `key=value` form, where nothing marks a stream boundary and a
    reader has to treat one chosen field as the start of the next record.
    """
    ffprobe = shutil.which("ffprobe")
    if ffprobe is None:
        raise MovieError(
            "no ffprobe on PATH: it is what checks a decoded movie actually opens, with the "
            "frames and the audio stream it should have (research/tooling-setup.md)"
        )
    out = _run(
        [
            ffprobe,
            "-v",
            "error",
            "-show_entries",
            "stream=codec_type,codec_name,nb_frames,sample_rate,channels",
            "-of",
            "json",
            str(path),
        ],
        cwd=path.parent,
        what=f"ffprobe of {path.name}",
    )
    try:
        return [
            {key: str(value) for key, value in stream.items()}
            for stream in json.loads(out)["streams"]
        ]
    except (ValueError, KeyError, AttributeError) as bad:
        raise MovieError(f"ffprobe of {path.name} returned no usable stream list: {bad}") from None


def verify_output(path: Path, frames: int) -> None:
    """Refuse a decode that lost the picture, the narration, or the tail of the movie.

    jPSXdec's `-psxav` pads the video to the disc's own A/V timing, so the file may hold a
    frame or two more than the extent has slots; it must never hold fewer, which is what a
    truncated or failed decode looks like.
    """
    streams = ffprobe_streams(path)
    video = [s for s in streams if s.get("codec_type") == "video"]
    audio = [s for s in streams if s.get("codec_type") == "audio"]
    if not video:
        raise MovieError(f"{path.name} has no video stream -- the decode produced nothing")
    if not audio:
        raise MovieError(
            f"{path.name} has no audio stream: the XA narration was not muxed in, which is "
            f"the whole point of decoding these (research/movies.md section 2.2)"
        )
    # ffprobe prints `nb_frames=N/A` -- not an empty field -- for a container that records
    # no frame count, so `int()` on it would end the whole batch with a traceback instead
    # of a refusal, and every movie after this one would go undecoded.
    counted = video[0].get("nb_frames", "")
    if not counted.isdigit():
        raise MovieError(
            f"{path.name}: ffprobe reports nb_frames={counted or '(nothing)'!r}, so whether "
            f"the decode kept all {frames} frames cannot be checked"
        )
    if int(counted) < frames:
        raise MovieError(
            f"{path.name} holds {counted} frames, fewer than the {frames} frame slots in "
            f"the extent -- the decode stopped early"
        )


def may_skip(out_path: Path, movie: MovieFile, *, force: bool) -> bool:
    """Whether this run can leave an existing output alone.

    The file is checked before it is believed: an interrupted run leaves a part-written
    movie, and every later run would otherwise skip past it without a word. It is a
    `verify_output` check and not a provenance one, so it says the file is playable and
    long enough, not that this tool produced it from this dump.
    """
    if force or not out_path.is_file():
        return False
    verify_output(out_path, movie.frames)
    return True


@dataclass(frozen=True)
class Decoded:
    """What a decode learned that the caller did not already know from the `MovieFile`."""

    size: int
    elapsed: float


def decode_one(
    image: DiscImage,
    movie: MovieFile,
    out_dir: Path,
    *,
    java: str,
    jar: Path,
    scratch: Path,
) -> Decoded:
    """Slice, index, decode and check one movie. The raw slice is scratch and is deleted."""
    started = time.monotonic()
    scratch.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{movie.name}.avi"
    raw = scratch / movie.name  # jPSXdec names its output after this file
    index = scratch / f"{movie.name}.idx"
    produced: Path | None = None  # named only once the index gives the video item's number
    try:
        sectors = slice_movie(image, movie, raw)
        if sectors != movie.sectors:
            raise MovieError(f"{movie.path}: sliced {sectors} sectors, expected {movie.sectors}")
        _run([java, "-jar", str(jar), "-f", raw.name, "-x", index.name], scratch, "jPSXdec index")
        items = parse_index(index.read_text(encoding="utf-8"))
        videos = [item for item in items if item.type == "Video"]
        if len(videos) != 1:
            raise MovieError(
                f"{movie.path}: jPSXdec's index holds {len(videos)} video items, expected 1"
            )
        video = videos[0]
        _check_index_agrees(movie, video)
        _run(
            [
                java,
                "-jar",
                str(jar),
                "-x",
                index.name,
                "-i",
                str(video.number),
                "-vf",
                "avi:mjpg",
                "-q",
                "psx",
                "-psxav",
            ],
            scratch,
            f"jPSXdec decode of {movie.name}",
        )
        produced = scratch / f"{movie.name}[{video.number}].avi"
        if not produced.is_file():
            raise MovieError(f"jPSXdec wrote no {produced.name} for {movie.path}")
        verify_output(produced, movie.frames)  # before it is published -- see `may_skip`
        out_dir.mkdir(parents=True, exist_ok=True)
        shutil.move(str(produced), out_path)
    finally:
        # A decode that failed verification must not sit in the scratch directory holding
        # its 160 MB until the whole run ends.
        for leftover in (raw, index, produced):
            if leftover is not None:
                leftover.unlink(missing_ok=True)
    return Decoded(size=out_path.stat().st_size, elapsed=time.monotonic() - started)


def _check_index_agrees(movie: MovieFile, video: IndexItem) -> None:
    """jPSXdec's own count against the extent arithmetic `SECTORS_PER_FRAME` rests on."""
    stride = video.fields.get("Sectors/Frame", "")
    if stride != f"{SECTORS_PER_FRAME}/1":
        raise MovieError(
            f"{movie.path}: jPSXdec reads {stride or '?'} sectors per frame, not "
            f"{SECTORS_PER_FRAME}/1 -- research/movies.md section 4 and this module's "
            f"frame arithmetic both assume it"
        )
    counted = int(video.fields.get("Frame Count", "0"))
    if counted != movie.frames:
        raise MovieError(
            f"{movie.path}: jPSXdec counts {counted} frames, the extent has "
            f"{movie.sectors} sectors = {movie.frames} frame slots"
        )


# --- the command --------------------------------------------------------------------------------


def main_movies(
    source: Path,
    out_dir: Path,
    *,
    tsv_only: bool,
    tsv_path: Path,
    force: bool,
    only: list[str] | None,
) -> int:
    """The `boku movies` command body. Returns a process exit status."""
    try:
        if not source.is_file():
            raise MovieError(
                f"no image at {source}: run `./make.sh import` first. The repo ships none "
                f"of the game"
            )
        if tsv_only and only:
            raise MovieError(
                "--only names movies to decode, and --tsv decodes nothing; the table is "
                "always regenerated whole"
            )
        entries = parse_movie_ids(MOVIES_MD.read_text(encoding="utf-8"))
        with DiscImage(source) as image:
            on_disc = iki_entries(image)
            # The table is always the whole list: `--only` picks what to spend decode time
            # on, and a table holding only that would be a table of one movie.
            frames_by_file = {movie.name: movie.frames for movie in on_disc}
            if tsv_only:
                path = write_tsv(frames_by_file, tsv_path, entries=entries)
                print(f"{path}: {len(entries)} ids")
                return 0
            _decode_all(
                image,
                _wanted(on_disc, only),
                out_dir,
                entries=entries,
                force=force,
            )
            path = write_tsv(frames_by_file, tsv_path, entries=entries)
            print(f"{path} regenerated; fill in what_it_shows from watching them")
        return 0
    except (MovieError, DiscError) as refusal:
        print(f"boku movies: refused: {refusal}", file=sys.stderr)
        return 2


def _wanted(on_disc: list[MovieFile], only: list[str] | None) -> list[MovieFile]:
    if not only:
        return on_disc
    names = {name.upper() for name in only}
    chosen = [movie for movie in on_disc if movie.name.upper() in names]
    missing = names - {movie.name.upper() for movie in chosen}
    if missing:
        raise MovieError(f"no such movie on the image: {', '.join(sorted(missing))}")
    return chosen


def _decode_all(
    image: DiscImage,
    movies: list[MovieFile],
    out_dir: Path,
    *,
    entries: list[MovieId],
    force: bool,
) -> None:
    java = java_binary()
    jar = jpsxdec_jar()
    out_dir.mkdir(parents=True, exist_ok=True)
    by_file = ids_by_file(entries)
    total_size = 0
    total_time = 0.0
    done = 0
    # The scratch lives beside the output so that publishing a decoded movie is a rename
    # rather than a copy of up to 163 MB across filesystems.
    with tempfile.TemporaryDirectory(prefix=".boku-movies-", dir=out_dir) as scratch_name:
        for movie in movies:
            out_path = out_dir / f"{movie.name}.avi"
            if may_skip(out_path, movie, force=force):
                detail = "(already there)"
            else:
                result = decode_one(
                    image, movie, out_dir, java=java, jar=jar, scratch=Path(scratch_name)
                )
                done += 1
                total_size += result.size
                total_time += result.elapsed
                detail = f"({result.size / 1e6:.1f} MB, {result.elapsed:.1f}s)"
            ids = ",".join(str(i) for i in by_file.get(movie.name, [])) or "-"
            print(
                f"id {ids:<16} {movie.name:<6} {movie.frames:>5} frames "
                f"{movie.frames / FPS:>7.1f}s  {out_path}  {detail}"
            )
    print(
        f"\n{done} movie(s) decoded in {total_time:.1f}s, {total_size / 1e6:.1f} MB "
        f"written to {out_dir}/"
    )


def add_arguments(parser: argparse.ArgumentParser) -> argparse.ArgumentParser:
    parser.add_argument(
        "source",
        nargs="?",
        type=Path,
        default=DEFAULT_IMAGE,
        metavar="IMAGE",
        help=f"raw image to read (default: {DEFAULT_IMAGE.relative_to(REPO_ROOT)})",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=DEFAULT_OUT_DIR,
        metavar="DIR",
        help=f"where the movies go (default: {DEFAULT_OUT_DIR.relative_to(REPO_ROOT)}/)",
    )
    parser.add_argument(
        "--tsv",
        action="store_true",
        help=(
            f"only regenerate {MOVIES_TSV.relative_to(REPO_ROOT)} and stop -- no decoding, "
            f"so it needs neither Java nor jPSXdec"
        ),
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="decode a movie again even though its output is already there",
    )
    parser.add_argument(
        "--only",
        nargs="+",
        metavar="NAME",
        help="decode just these files, by name (M27, M010, ...)",
    )
    parser.set_defaults(
        run=lambda args: main_movies(
            args.source,
            args.out,
            tsv_only=args.tsv,
            tsv_path=MOVIES_TSV,
            force=args.force,
            only=args.only,
        )
    )
    return parser
